{% set name = "amp-atomistics" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amp-atomistics-{{ version }}.tar.gz
  sha256: 91c097930f71534bbd8cedc922ef35a2883ab2e10587e1e95c04ce23ad34233f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - matplotlib-base
    - ase
    - pyzmq
    - pexpect
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - amp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/andrewpeterson/amp
  summary: Atomistic Machine-learning Package
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
